server:
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

  mvc:
    view:
      prefix: classpath:/static/
      suffix: .html

    ignore-default-model-on-redirect: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.backend.mapper