server:
  port: 9090

logging:
  level:
    org.springframework: debug

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  messages:
    basename: messages
