server:
  port: 9090

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    prefix:  classpath:templates/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
  mvc:
    ignore-default-model-on-redirect: false


