server:
  port: 9090

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study01
    username: root
    password: 1234



  thymeleaf:
    prefix:  classpath:templates/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
  mvc:
    ignore-default-model-on-redirect: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.board.mapper