spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # hibernate 사용 설정
    hibernate:
      # 애플리케이션 실행 시점에 테이블을 다 지우고, 내가 가진 entity 정보를 보고 다시 테이블 자동 생성
      # if exists drop table 해주고 다시 만들어준다고 보면 된다.
      ddl-auto: update
    properties:
      hibernate:
        # JPA 처리 시에 발생하는 SQL을 보여줄 것인지 결정
        show_sql: true
        # 실제 JPA의 구현체인 Hibernate가 동작하면서 발생하는 SQL을 포맷팅해서 출력합니다.
        # 실행되는 SQL의 가독성을 높여 줍니다.
        format_sql: true
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false

  mustache:
    suffix: .mustache
    prefix: classpath:/templates/


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study01
    username: root
    password: 1234

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor: trace

